#page title
page_title: GrateDate # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1488266331 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
#playstore_link:# Enter Google Play Store URL. presskit_download_link:# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: GRateDate # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Choose Better. Date Smarter.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Multiverse Studios
your_link:
your_city:
email_address: contact@gratedate.app
facebook_username: Gratedate
instagram_username: /grate_date
twitter_username: grate_date
github_username:
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: With GRateDate
    description: You can rate, track, and compare dates using questions designed by psychologists.
    fontawesome_icon_name: check

  - title: Select your dating priorities
    description: Select the dating priorities that matter to you.
    fontawesome_icon_name: list-ul

  - title: Better Rating
    description: Rate your partners based on psychologically curated questions
    fontawesome_icon_name: smile

  - title: Journal and Keep Track
    description: Keep a running journal for each date and remember the details.
    fontawesome_icon_name: history

  - title: Compare Dates
    description: Compare your dates and see who ranks at the top.
    fontawesome_icon_name: users

  - title: Analyze the Trends
    description: See how your date is trending and evaluate their strengths and weaknesses.
    fontawesome_icon_name: poll-h

  - title: Dating Uppers
    description: See how many positive qualities your dates have.
    fontawesome_icon_name: thumbs-up

  - title: Dating Downers
    description: See how many negative qualities your dates have.
    fontawesome_icon_name: thumbs-down

  - title: Red Flags
    description: See if your dates have any red flags to watch out for.
    fontawesome_icon_name: flag

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.0
topbar_title_color: "#ffffff"

cover_image: assets/background.png # Replace with alternative image path or image URL.
cover_overlay_color: "#ffffff"
cover_overlay_transparency: 0.0

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#3db7b9"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#E82120"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#3DB7B9"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
